definition: {
openapi: "3.0.0",
info: {
  title: "Terbang Tinggi App",
  version: "1.0",
  description: "test",
  contact: {
    email: "terbangtinggiapp@gmail.com",
    name: "Developer",
  },
servers: [
  {
     - description: "",
      url: "https://final-project-binar-1.vercel.app/",
  },
],
},
apis: ["routes/**/*.js"]
}